name: .NET Core Desktop

on:
  push:
    branches: [ "feature1" ]
  pull_request:
    branches: [ "feature1" ]
  workflow_dispatch: 
   inputs: 
      deployment_target:
        description: Choose target
        required: true
        default: smoke
        type: choice
        options:
          - smoke
          - regression

   schedule:
        - cron: '8 9 12 * *'

jobs:

  test:

    strategy:
      matrix:
        configuration: [Debug]

    runs-on: ubuntu-latest 

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    # Update Chrome driver stable version
    - name: Update Chrome # See https://stackoverflow.com/q/63651059/419956
      run: |
       wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
       sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
       sudo apt-get update
       sudo apt-get --only-upgrade install google-chrome-stable
    
    # Execute Smoke tests in the solution
    - name: Execute Smoke tests
      if: "github.event.inputs.deployment_target == 'smoke' || github.event.schedule == '8 9 12 * *'"
      run: dotnet test --filter Category=Smoke
      id: smoke

    # Execute Regression tests in the solution
    - name: Execute Regression tests
      if: "github.event.inputs.deployment_target == 'regression'"
      run: dotnet test --filter Category=Regression
      id: regression
    
    # Execute all unit tests in the solution
    - name: Execute unit tests
      if: steps.smoke.conclusion == 'skipped' && steps.regression.conclusion == 'skipped'
      run: dotnet test

    #
    - name: Load test report history
      uses: actions/checkout@v3
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Build test report
      uses: simple-elf/allure-report-action@v1.7
      if: always()
      with:
        gh_pages: gh-pages
        allure_history: allure-history
        allure_results: bin/Debug/net8.0/allure-results

    - name: Publish test report
      uses: peaceiris/actions-gh-pages@v3
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-history